name: restaurant_app_new
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <=3.3.2'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  sqflite: ^2.1.0
  flutter_slidable: ^2.0.0
  android_alarm_manager_plus: ^2.0.7
  flutter_local_notifications: ^9.4.0
  rxdart: ^0.27.3
  intl: ^0.17.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.3.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

